# L2R using re-exam dataset

In [3]:
import pandas as pd 
df = pd.read_csv('re-exam/Fold1/features_test.txt', sep = ' ')
df.head()

,0,qid:85,1:2.000000,2:1.386294,3:0.285714,4:0.267063,5:31.501670,6:9.711111,7:31.492372,8:1.326560,...,39:43.108309,40:5.858921,41:29.089976,42:3.370394,43:-29.090872,44:-29.420224,45:-28.870296,#docid,=,57950
0,0,qid:85,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:31.501670,6:9.711111,7:31.492372,8:0.000000,...,39:20.477488,40:3.179236,41:23.314461,42:3.149074,43:-32.789792,44:-31.904877,45:-31.730449,#docid,=,331965
1,0,qid:85,1:2.000000,2:1.386294,3:0.181818,4:0.174023,5:31.501670,6:9.711111,7:31.492372,8:0.826218,...,39:50.360276,40:3.213099,41:19.422023,42:2.966408,43:-37.951676,44:-37.753375,45:-38.489511,#docid,=,296434
2,0,qid:85,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:31.501670,6:9.711111,7:31.492372,8:0.000000,...,39:17.361593,40:2.041398,41:19.309687,42:2.960607,43:-34.874181,44:-35.034471,45:-35.309569,#docid,=,118306
3,0,qid:85,1:0.000000,2:0.000000,3:0.000000,4:0.000000,5:31.501670,6:9.711111,7:31.492372,8:0.000000,...,39:28.439236,40:1.808811,41:19.207724,42:2.955312,43:-34.402451,44:-35.156911,45:-34.529589,#docid,=,277077
4,0,qid:85,1:3.000000,2:2.079442,3:0.300000,4:0.285931,5:31.501670,6:9.711111,7:31.492372,8:1.270858,...,39:45.190202,40:3.768800,41:18.141063,42:2.898178,43:-39.248080,44:-38.586778,45:-39.078578,#docid,=,249306